//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EqCrm.SoapDigifact {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FELWSFRONTSoap", Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FELWSFRONT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SSLTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SecureTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FELWSFRONT() {
            this.Url = global::EqCrm.Properties.Settings.Default.EqCrm_SoapDigifact_FELWSFRONT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestTransactionCompletedEventHandler RequestTransactionCompleted;
        
        /// <remarks/>
        public event SSLTransactionCompletedEventHandler SSLTransactionCompleted;
        
        /// <remarks/>
        public event SecureTransactionCompletedEventHandler SecureTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/RequestTransaction", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionTag RequestTransaction(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3) {
            object[] results = this.Invoke("RequestTransaction", new object[] {
                        Requestor,
                        Transaction,
                        Country,
                        Entity,
                        User,
                        UserName,
                        Data1,
                        Data2,
                        Data3});
            return ((TransactionTag)(results[0]));
        }
        
        /// <remarks/>
        public void RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3) {
            this.RequestTransactionAsync(Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3, null);
        }
        
        /// <remarks/>
        public void RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3, object userState) {
            if ((this.RequestTransactionOperationCompleted == null)) {
                this.RequestTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestTransactionOperationCompleted);
            }
            this.InvokeAsync("RequestTransaction", new object[] {
                        Requestor,
                        Transaction,
                        Country,
                        Entity,
                        User,
                        UserName,
                        Data1,
                        Data2,
                        Data3}, this.RequestTransactionOperationCompleted, userState);
        }
        
        private void OnRequestTransactionOperationCompleted(object arg) {
            if ((this.RequestTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestTransactionCompleted(this, new RequestTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/SSLTransaction", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SSLTransaction(string Entity, string DataExchange) {
            object[] results = this.Invoke("SSLTransaction", new object[] {
                        Entity,
                        DataExchange});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SSLTransactionAsync(string Entity, string DataExchange) {
            this.SSLTransactionAsync(Entity, DataExchange, null);
        }
        
        /// <remarks/>
        public void SSLTransactionAsync(string Entity, string DataExchange, object userState) {
            if ((this.SSLTransactionOperationCompleted == null)) {
                this.SSLTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSSLTransactionOperationCompleted);
            }
            this.InvokeAsync("SSLTransaction", new object[] {
                        Entity,
                        DataExchange}, this.SSLTransactionOperationCompleted, userState);
        }
        
        private void OnSSLTransactionOperationCompleted(object arg) {
            if ((this.SSLTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SSLTransactionCompleted(this, new SSLTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/SecureTransaction", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SecureTransaction(string Entity, string DataExchange) {
            object[] results = this.Invoke("SecureTransaction", new object[] {
                        Entity,
                        DataExchange});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SecureTransactionAsync(string Entity, string DataExchange) {
            this.SecureTransactionAsync(Entity, DataExchange, null);
        }
        
        /// <remarks/>
        public void SecureTransactionAsync(string Entity, string DataExchange, object userState) {
            if ((this.SecureTransactionOperationCompleted == null)) {
                this.SecureTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSecureTransactionOperationCompleted);
            }
            this.InvokeAsync("SecureTransaction", new object[] {
                        Entity,
                        DataExchange}, this.SecureTransactionOperationCompleted, userState);
        }
        
        private void OnSecureTransactionOperationCompleted(object arg) {
            if ((this.SecureTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SecureTransactionCompleted(this, new SecureTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class TransactionTag {
        
        private FactRequest requestField;
        
        private FactResponse responseField;
        
        private FactResponseData responseDataField;
        
        /// <remarks/>
        public FactRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public FactResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public FactResponseData ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactRequest {
        
        private System.Guid requestorField;
        
        private string requestorNameField;
        
        private bool requestorActiveField;
        
        private Transactions transactionField;
        
        private string countryField;
        
        private string entityField;
        
        private System.Guid userField;
        
        private string userNameField;
        
        private System.Guid idField;
        
        private System.DateTime timeStampField;
        
        /// <remarks/>
        public System.Guid Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
            }
        }
        
        /// <remarks/>
        public string RequestorName {
            get {
                return this.requestorNameField;
            }
            set {
                this.requestorNameField = value;
            }
        }
        
        /// <remarks/>
        public bool RequestorActive {
            get {
                return this.requestorActiveField;
            }
            set {
                this.requestorActiveField = value;
            }
        }
        
        /// <remarks/>
        public Transactions Transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public enum Transactions {
        
        /// <remarks/>
        BASE,
        
        /// <remarks/>
        NO_TRANSACTION,
        
        /// <remarks/>
        CONVERT_NATIVE_XML,
        
        /// <remarks/>
        GET_MTE_BATCH,
        
        /// <remarks/>
        PROCESS_BATCH,
        
        /// <remarks/>
        SYSTEM_REQUEST,
        
        /// <remarks/>
        RECEIVE_BATCH,
        
        /// <remarks/>
        ENROLL_CERT,
        
        /// <remarks/>
        GET_XML,
        
        /// <remarks/>
        GET_HTML,
        
        /// <remarks/>
        GET_XML_AND_HTML,
        
        /// <remarks/>
        CANCEL_XML,
        
        /// <remarks/>
        MARK_XML_AS_PAID,
        
        /// <remarks/>
        MARK_XML_AS_UNPAID,
        
        /// <remarks/>
        SEARCH_BASIC,
        
        /// <remarks/>
        GET_MONTHLY_REPORT,
        
        /// <remarks/>
        GET_MONTHLY_REPORT_FOR_PROVIDER,
        
        /// <remarks/>
        GET_FOLIOS_BY_RFC,
        
        /// <remarks/>
        DOES_ASSIGNMENT_EXIST,
        
        /// <remarks/>
        CANCEL_XML_BY_INTERNAL_ID,
        
        /// <remarks/>
        ACTIVATE_ASSIGNMENT,
        
        /// <remarks/>
        COUNT_ACTIVE_ASSIGNMENTS,
        
        /// <remarks/>
        GET_DOCUMENT,
        
        /// <remarks/>
        AUTHENTICATE_USER,
        
        /// <remarks/>
        GET_ACCOUNT,
        
        /// <remarks/>
        DISTRIBUTE,
        
        /// <remarks/>
        QUEUE_FOR_DISTRIBUTION,
        
        /// <remarks/>
        GET_EFFECTIVE_RIGHTS,
        
        /// <remarks/>
        EXEC_STORED_PROC,
        
        /// <remarks/>
        GET_USER_INFO,
        
        /// <remarks/>
        RECEIVE,
        
        /// <remarks/>
        GET_PREVIEW,
        
        /// <remarks/>
        RETRIEVE_DOCUMENT,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_PAID,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_NOT_PAID,
        
        /// <remarks/>
        CANCEL_DOCUMENT,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_DELETED,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_NOT_DELETED,
        
        /// <remarks/>
        GET_ADDENDA_RECEIVERS,
        
        /// <remarks/>
        REQUEST_PASSWORD_CHANGE,
        
        /// <remarks/>
        CHANGE_DOCUMENT_SUCURSAL,
        
        /// <remarks/>
        CREATE_ACCOUNT_AS_OWNER,
        
        /// <remarks/>
        CREATE_PASSWORD,
        
        /// <remarks/>
        PASSWORD_FORGOT,
        
        /// <remarks/>
        CREATE_USER,
        
        /// <remarks/>
        INCREMENT_BUNDLE_SIZE,
        
        /// <remarks/>
        TIMBRAR,
        
        /// <remarks/>
        LOOKUP_ISSUED_INTERNAL_ID,
        
        /// <remarks/>
        VALIDATE_CERT,
        
        /// <remarks/>
        BATCH_SERIAL_OPERATIONS,
        
        /// <remarks/>
        PROCESS_LCO,
        
        /// <remarks/>
        ENROLL_THIRD_PARTY_CERT,
        
        /// <remarks/>
        CANCEL_CFDI,
        
        /// <remarks/>
        UPDATE_ACCOUNT_DATA,
        
        /// <remarks/>
        ASSIGN_ACCOUNT_REQUESTOR,
        
        /// <remarks/>
        UPDATE_USER_DATA,
        
        /// <remarks/>
        UPDATE_ADMIN_USER_DATA,
        
        /// <remarks/>
        CREATE_ADMIN_USER,
        
        /// <remarks/>
        UPSERT_GRAPHIC_REPRESENTATION,
        
        /// <remarks/>
        LOOKUP_ISSUED_BATCH_AND_SERIAL,
        
        /// <remarks/>
        CREATE_TIMBRAR_ACCOUNT,
        
        /// <remarks/>
        CREATE_TIMBRAR_ISSUER_ACCOUNT,
        
        /// <remarks/>
        LOOKUP_GUATEMALIAN_ISSUED,
        
        /// <remarks/>
        CLOSE_MONTH,
        
        /// <remarks/>
        SYSTEM_REQUEST1,
        
        /// <remarks/>
        GET_ACUSE,
        
        /// <remarks/>
        GRAPH_REQUEST,
        
        /// <remarks/>
        CANCEL_SINGLE_CFDI,
        
        /// <remarks/>
        CONFIG_REFRESH,
        
        /// <remarks/>
        RECERTIFICAR,
        
        /// <remarks/>
        GET_CRFM_STATUS,
        
        /// <remarks/>
        GET_CRFM_STATUS_EXPORT,
        
        /// <remarks/>
        EXEC_STORED_PROC_GT,
        
        /// <remarks/>
        GETCRFM_SUMMARY,
        
        /// <remarks/>
        GET_COPY_NOTIFICATION_BY_SAT_REQUEST,
        
        /// <remarks/>
        GET_VALIDATE_NOTIFICATION_BY_SAT_REQUEST,
        
        /// <remarks/>
        GET_DETAILTAXID_BY_SAT_REQUEST,
        
        /// <remarks/>
        EXEC_STORED_SAT,
        
        /// <remarks/>
        AUTHENTICATE_USER_ANDROID,
        
        /// <remarks/>
        TAXID_VERIFY,
        
        /// <remarks/>
        EFACEADMIN_CREATE_ACCOUNT,
        
        /// <remarks/>
        EFACEADMIN_GET_INFO_ACCOUNT,
        
        /// <remarks/>
        EFACEADMIN_CREATE_CRFM,
        
        /// <remarks/>
        EFACEADMIN_GET_STATUS_CRFM,
        
        /// <remarks/>
        EFACEADMIN_ADD_DOCUMENTOS,
        
        /// <remarks/>
        SHARED_INFO_EFACE,
        
        /// <remarks/>
        CERTIFICATE_DTE_XML,
        
        /// <remarks/>
        CERTIFICATE_DTE_XML_TOSIGN,
        
        /// <remarks/>
        CANCEL_FEL,
        
        /// <remarks/>
        CANCEL_FEL_XML,
        
        /// <remarks/>
        CANCEL_FEL_XMLSIGNED,
        
        /// <remarks/>
        CANCEL_FEL_XMLTOSIGNED,
        
        /// <remarks/>
        FEL_GET_DOCUMENT,
        
        /// <remarks/>
        FEL_GET_INFO_SIGNATURE,
        
        /// <remarks/>
        EXEC_STORED_PROC_AUX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponseData {
        
        private string responseData1Field;
        
        private string responseData2Field;
        
        private string responseData3Field;
        
        private System.Data.DataSet responseDataSetField;
        
        /// <remarks/>
        public string ResponseData1 {
            get {
                return this.responseData1Field;
            }
            set {
                this.responseData1Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseData2 {
            get {
                return this.responseData2Field;
            }
            set {
                this.responseData2Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseData3 {
            get {
                return this.responseData3Field;
            }
            set {
                this.responseData3Field = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ResponseDataSet {
            get {
                return this.responseDataSetField;
            }
            set {
                this.responseDataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class BatchID {
        
        private string batchIdField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        /// <remarks/>
        public string BatchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        public string BatchTimeStamp {
            get {
                return this.batchTimeStampField;
            }
            set {
                this.batchTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorCountry {
            get {
                return this.batchRequestorCountryField;
            }
            set {
                this.batchRequestorCountryField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorEntity {
            get {
                return this.batchRequestorEntityField;
            }
            set {
                this.batchRequestorEntityField = value;
            }
        }
        
        /// <remarks/>
        public string BatchPosition {
            get {
                return this.batchPositionField;
            }
            set {
                this.batchPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class DocID {
        
        private string countryField;
        
        private string entityField;
        
        private string fiscalNameField;
        
        private string aYearField;
        
        private string aNumberField;
        
        private string batchField;
        
        private string serialField;
        
        private string documentGUIDField;
        
        private string issuedTimeStampField;
        
        private string enrolledTimeStampField;
        
        private string paidTimeStampField;
        
        private string cancelledTimeStampField;
        
        private string internalIDField;
        
        private string batchIDField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        private string receiverCountryField;
        
        private string receiverEntityField;
        
        private string receiverTaxIDField;
        
        private string receiverNameField;
        
        private string claveAgenteField;
        
        private string numeroDePolizaField;
        
        private string currencyField;
        
        private string totalAmountField;
        
        private string type1Field;
        
        private string type2Field;
        
        private string suggestedFileNameField;
        
        private string suggestedFileName2Field;
        
        private string fEL_FACEIDField;
        
        private string fEL_INFODETAILSField;
        
        private string fEL_ERRORField;
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public string FiscalName {
            get {
                return this.fiscalNameField;
            }
            set {
                this.fiscalNameField = value;
            }
        }
        
        /// <remarks/>
        public string AYear {
            get {
                return this.aYearField;
            }
            set {
                this.aYearField = value;
            }
        }
        
        /// <remarks/>
        public string ANumber {
            get {
                return this.aNumberField;
            }
            set {
                this.aNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentGUID {
            get {
                return this.documentGUIDField;
            }
            set {
                this.documentGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string IssuedTimeStamp {
            get {
                return this.issuedTimeStampField;
            }
            set {
                this.issuedTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string EnrolledTimeStamp {
            get {
                return this.enrolledTimeStampField;
            }
            set {
                this.enrolledTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string PaidTimeStamp {
            get {
                return this.paidTimeStampField;
            }
            set {
                this.paidTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string CancelledTimeStamp {
            get {
                return this.cancelledTimeStampField;
            }
            set {
                this.cancelledTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
            }
        }
        
        /// <remarks/>
        public string BatchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public string BatchTimeStamp {
            get {
                return this.batchTimeStampField;
            }
            set {
                this.batchTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorCountry {
            get {
                return this.batchRequestorCountryField;
            }
            set {
                this.batchRequestorCountryField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorEntity {
            get {
                return this.batchRequestorEntityField;
            }
            set {
                this.batchRequestorEntityField = value;
            }
        }
        
        /// <remarks/>
        public string BatchPosition {
            get {
                return this.batchPositionField;
            }
            set {
                this.batchPositionField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverCountry {
            get {
                return this.receiverCountryField;
            }
            set {
                this.receiverCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverEntity {
            get {
                return this.receiverEntityField;
            }
            set {
                this.receiverEntityField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverTaxID {
            get {
                return this.receiverTaxIDField;
            }
            set {
                this.receiverTaxIDField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverName {
            get {
                return this.receiverNameField;
            }
            set {
                this.receiverNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClaveAgente {
            get {
                return this.claveAgenteField;
            }
            set {
                this.claveAgenteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDePoliza {
            get {
                return this.numeroDePolizaField;
            }
            set {
                this.numeroDePolizaField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        public string Type1 {
            get {
                return this.type1Field;
            }
            set {
                this.type1Field = value;
            }
        }
        
        /// <remarks/>
        public string Type2 {
            get {
                return this.type2Field;
            }
            set {
                this.type2Field = value;
            }
        }
        
        /// <remarks/>
        public string SuggestedFileName {
            get {
                return this.suggestedFileNameField;
            }
            set {
                this.suggestedFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string SuggestedFileName2 {
            get {
                return this.suggestedFileName2Field;
            }
            set {
                this.suggestedFileName2Field = value;
            }
        }
        
        /// <remarks/>
        public string FEL_FACEID {
            get {
                return this.fEL_FACEIDField;
            }
            set {
                this.fEL_FACEIDField = value;
            }
        }
        
        /// <remarks/>
        public string FEL_INFODETAILS {
            get {
                return this.fEL_INFODETAILSField;
            }
            set {
                this.fEL_INFODETAILSField = value;
            }
        }
        
        /// <remarks/>
        public string FEL_ERROR {
            get {
                return this.fEL_ERRORField;
            }
            set {
                this.fEL_ERRORField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponse {
        
        private bool resultField;
        
        private System.DateTime timeStampField;
        
        private string lastResultField;
        
        private int codeField;
        
        private string descriptionField;
        
        private string hintField;
        
        private string dataField;
        
        private string processorField;
        
        private DocID identifierField;
        
        private BatchID batchIdentifierField;
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public string LastResult {
            get {
                return this.lastResultField;
            }
            set {
                this.lastResultField = value;
            }
        }
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Hint {
            get {
                return this.hintField;
            }
            set {
                this.hintField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Processor {
            get {
                return this.processorField;
            }
            set {
                this.processorField = value;
            }
        }
        
        /// <remarks/>
        public DocID Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public BatchID BatchIdentifier {
            get {
                return this.batchIdentifierField;
            }
            set {
                this.batchIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void RequestTransactionCompletedEventHandler(object sender, RequestTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionTag Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionTag)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SSLTransactionCompletedEventHandler(object sender, SSLTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSLTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SSLTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void SecureTransactionCompletedEventHandler(object sender, SecureTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SecureTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SecureTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591